FROM registry.access.redhat.com/hi/nodejs:24.18.0-builder

USER root

RUN npm install --global pnpm@10.17.1 \
    && test "$(pnpm --version)" = "10.17.1"

RUN groupadd nonroot \
    && useradd --gid nonroot --create-home --shell /bin/bash nonroot \
    && mkdir -p /home/nonroot/.local/share/pnpm/store \
    && chown -R nonroot:nonroot /home/nonroot

ENV HOME=/home/nonroot
USER nonroot
